### ISSUE TITLE
[Technology] Setting Hostname of Container as Host Machine's Hostname

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/blog#9]
## Nugget

- describe with Alpine container how a standard env variable available for user e.g. `HOSTNAME` or `HOST` will not set the container's hostname
- need to either `export HOSTNAME` or `export HOST` or set the same in `~/.bashrc` file
- The env variables need to be available `printenv` in the session

### Example

```yaml
services:
  test:
    image: alpine:latest
    container_name: hostname-tester
    hostname: ${NAME}
    command:
      - hostname
```
